### ISSUE TITLE
Remove the loading indicator or activity indicator

### ISSUE THREAD

**Issue by halid96** [douglasjunior/react-native-recaptcha-that-works#41]
I am using the configuration below, however, it is not fully invisible. The activity indicator appears on iOS. The StatusBar appears on Android.
 
 I am using the following configuration. modalProps prop not rewrites modalProps props correctly. 
 
```
                    <View style={{ display: 'none' }}>
                        <Recaptcha
                            style={{ display: 'none' }}
                            ref={recaptcha}
                            siteKey="6LcsO5sUAAAAADhfEx8vydV0wfzsU2nP1DjHjaZN"
                            baseUrl="https://www.trollflix.com"
                            onVerify={onVerify}
                            size="invisible"
                            hideBadge={true}
                            modalProps={{ visible: false, animationType: 'none', transparent: true, supportedOrientations: ['landscape-right'], statusBarTranslucent: true }}
                        />
                    </View>
```

**Comment by douglasjunior** [comment]
You can change de loading component with `loadingComponent` prop, but I don't think that is a good option to completely remove it.

Because reCaptcha can open de challenge popup in the front of your screen, like this:

![image](https://user-images.githubusercontent.com/1512341/229500714-6f8310a4-012c-440e-9342-c1d85104f1fc.png)

About the status bar on Android, you can change it with `statusBarTranslucent` in `modalProps` https://reactnative.dev/docs/modal#statusbartranslucent-android
