### ISSUE TITLE
Image Selection Card White Background

### ISSUE THREAD

**Issue by itsnyx** [douglasjunior/react-native-recaptcha-that-works#52]
Hello, when image selection pop up activates it displays a white background behind it, how can i remove this white background and make it transparent ?

Cancel button is in footer, and my app background is black:
![image](https://github.com/douglasjunior/react-native-recaptcha-that-works/assets/74738973/dc2f0a15-c887-40e8-b400-eda392d1419f)
but when image selection pop up activates it shows a white background !

![image](https://github.com/douglasjunior/react-native-recaptcha-that-works/assets/74738973/f5f959a3-f84b-4794-833b-2f15a3ce9522)

**Comment by douglasjunior** [comment]
Could be something that the reCAPTCHA itself creates in background, because in the library all the "parents" are set as transparent:

https://github.com/douglasjunior/react-native-recaptcha-that-works/blob/cf4607a67b42187acf3b55ae58ab35b0a1a06eda/src/get-template.ts#L183-L191

Aside of this, the WebView you can customize by `style` prop and the Modal by the `modalProps.style` prop.

**Comment by itsnyx** [comment]
@douglasjunior what about changing it max-height property to prevent this?

**Comment by douglasjunior** [comment]
The problem is that we can't know the exactly `height` of the reCAPTCHA popup. From one day to another, Google can decide to change de popup UI/UX and the library will be broken.

But you can set maxHeight on the `style` prop to limit the WebView height.
